name = "waffle's Pack (Sodium)"
author = "wafflecoffee"
version = "2021.5.5"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e12fe5b63ed7f7c0c4f7f522b6191132c7bfd1accdbbc98edd0ad98a8460de93"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.3", "1.16.2"]
