name = "waffle's Pack (Sodium Modified)"
author = "wafflecoffee"
version = "2021.5.6"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff4f76506bf4afd74a89cc356bd44bf3c90abd9f99a28bac4050cbe80fd7df5f"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.3", "1.16.2"]
