name = "waffle's Pack (OptiFine)"
author = "wafflecoffee"
version = "2021.5.5"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1727e35fecc95284802036f845e8389f394f09b9a1a9d3c68d539c755c8d65d3"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.3", "1.16.2"]
